Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('KERNEL_BAREMETAL') and GetDepend('AIC_TSEN_TEST'):
    src += Glob('test_tsen.c')

group = DefineGroup('test-tsen', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
