Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('AIC_HRTIMER_DRV_TEST') and GetDepend('RT_USING_FINSH'):
    src = Glob('*.c')

group = DefineGroup('test-hrtimer', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
