Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []

if GetDepend('AIC_I2C_DRV_TEST') and GetDepend('PKG_USING_AT24CXX'):
    src = Glob('*.c')

group = DefineGroup('test-i2c', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
