Import('RTT_ROOT')
Import('rtconfig')
import os
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
