Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('AIC_MTD_LOAD_FILE_TEST'):
    src = Glob('*.c')

group = DefineGroup('test-mtd-load-file', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
