Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('AIC_WDT_DRV_TEST'):
    src = Glob('*.c')

group = DefineGroup('test-wdt', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
