Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd + '/../include/osal', ]

group = DefineGroup('aic_osal', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
