# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd     = GetCurrentDir()
src     = Glob('upg_detect.c')
src     += Glob('upg_detect_pin.c')

if GetDepend('AIC_RTC_DRV'):
    ver = GetConfigValue('AIC_RTC_DRV_VER')
    ver = ver.replace('"','')
    src += Glob('upg_detect_rtc_v%s.c' % ver)

if GetDepend('AIC_WRI_DRV'):
    ver = GetConfigValue('AIC_WRI_DRV_VER')
    ver = ver.replace('"','')
    src += Glob('upg_detect_wri_v%s.c' % ver)

CPPPATH = [cwd]
ASFLAGS = ''

group = DefineGroup('BLDRV', src, depend = [''], CPPPATH = CPPPATH, ASFLAGS = ASFLAGS)

Return('group')
