Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('KERNEL_BAREMETAL') and GetDepend('AIC_SPINAND_DRV_TEST'):
    src += Glob('spinand.c')

group = DefineGroup('test-spinand', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
