Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

src = Glob('*.c')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include/', ]

group = DefineGroup('aic_debug', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
