# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd     = GetCurrentDir()
group = []
if GetDepend('LPKG_USING_FDTLIB'):
    src     = Glob('*.c')
    CPPPATH = [cwd]
    ASFLAGS = ''

    group = DefineGroup('BLDRV', src, depend = [''], CPPPATH = CPPPATH, ASFLAGS = ASFLAGS)

Return('group')