Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd, ]
src = []

if GetDepend('AIC_MTD_BARE_TEST'):
    src += Glob('mtd.c')

CFLAGS = ' -c -ffunction-sections'

group = DefineGroup('test-mtd', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
