Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('KERNEL_BAREMETAL') and GetDepend('AIC_SPINOR_DRV_TEST'):
    src += Glob('spinor.c')

group = DefineGroup('test-spinor', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
