Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = []

if GetDepend('AIC_TOUCH_PANEL_GT911'):
    CPPPATH.append(cwd + '/gt911/inc')
    src += Glob('gt911/src/*.c')

if GetDepend('AIC_TOUCH_PANEL_FT7411'):
    CPPPATH.append(cwd + '/ft7411/inc')
    src += Glob('ft7411/src/*.c')

if GetDepend('AIC_TOUCH_PANEL_GSL1680'):
    CPPPATH.append(cwd + '/gsl1680/inc')
    src += Glob('gsl1680/src/*.c')

group = DefineGroup('touch', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
