Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('KERNEL_BAREMETAL') and GetDepend('AIC_GPIO_DRV_TEST'):
    src += Glob('test_gpio.c')

group = DefineGroup('test-gpio', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
