Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('KERNEL_BAREMETAL') and GetDepend('AIC_HRTIMER_DRV_TEST'):
    src += Glob('test_hrtimer.c')

group = DefineGroup('test-hrtimer', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
